/* Orellana Atlas 0.3 — aplicación sin dependencias externas.
 * Proyección de visualización: Web Mercator. Coordenadas de usuario: WGS84.
 * Las imágenes se solicitan por WMS; no se incluyen cartas ni teselas descargadas.
 */
'use strict';
(() => {
const $=id=>document.getElementById(id), $$=s=>Array.from(document.querySelectorAll(s));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>globalThis.crypto?.randomUUID?.()||`oa-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,11)}`;
const num=v=>{const t=String(v??'').trim().replace(',','.');return t===''?NaN:Number(t);};
const coordOK=c=>Array.isArray(c)&&c.length>=2&&Number.isFinite(c[0])&&Number.isFinite(c[1])&&Math.abs(c[0])<=180&&Math.abs(c[1])<=85;
const today=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};
const fmtDist=m=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2).replace('.',',')} km`;
const R=6371008.8, MERC=20037508.342789244, DEG=Math.PI/180, HOME={center:[-5.444,39.046],zoom:12.1};
function xy(c){const lat=clamp(c[1],-85.05112878,85.05112878)*DEG;return [(c[0]+180)/360,(1-Math.log(Math.tan(lat)+1/Math.cos(lat))/Math.PI)/2];}
function lonlat(p){return [p[0]*360-180,Math.atan(Math.sinh(Math.PI*(1-2*p[1])))/DEG];}
function distance(a,b){const dlat=(b[1]-a[1])*DEG,dlon=(b[0]-a[0])*DEG;const x=Math.sin(dlat/2)**2+Math.cos(a[1]*DEG)*Math.cos(b[1]*DEG)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(clamp(x,0,1)));}
function pathLength(coords){let d=0;for(let i=1;i<coords.length;i++)d+=distance(coords[i-1],coords[i]);return d;}
function destination(c,m,b){const a=m/R,t=b*DEG,lat=c[1]*DEG,lng=c[0]*DEG;const la=Math.asin(Math.sin(lat)*Math.cos(a)+Math.cos(lat)*Math.sin(a)*Math.cos(t));const lo=lng+Math.atan2(Math.sin(t)*Math.sin(a)*Math.cos(lat),Math.cos(a)-Math.sin(lat)*Math.sin(la));return [lo/DEG,la/DEG];}
function bearing(a,b){const la=a[1]*DEG,lb=b[1]*DEG,dl=(b[0]-a[0])*DEG;return (Math.atan2(Math.sin(dl)*Math.cos(lb),Math.cos(la)*Math.sin(lb)-Math.sin(la)*Math.cos(lb)*Math.cos(dl))/DEG+360)%360;}
const cardinal=d=>['N','NE','E','SE','S','SO','O','NO'][Math.round(d/45)%8];
const fmtWraps=m=>`${(m/state.settings.wrapM).toFixed(1).replace('.',',')} vueltas`;
const fmtFromCamp=(camp,c)=>{const d=distance(camp,c),b=bearing(camp,c);return {d,b,text:`${fmtDist(d)} · ${fmtWraps(d)} · ${Math.round(b)}° ${cardinal(b)}`,short:`${Math.round(d)} m · ${(d/state.settings.wrapM).toFixed(1).replace('.',',')} v · ${Math.round(b)}°`};};
const KINDS={camp:['Puesto','#e4b478'],point:['Punto de interés','#71dfc3'],bait:['Zona de cebado','#c7f36b'],bite:['Zona de picadas','#ff7fb0'],snag:['Enganche / obstáculo','#ff6b5b'],dropoff:['Cambio de fondo','#b99cff'],riverbed:['Cauce antiguo','#5fb4ff'],structure:['Estructura observada','#f2d16b'],sounding:['Medición de sonda','#8ecafb']};
const BOTTOMS={'':'Sin dato',grava:'Grava',arena:'Arena',fango:'Fango / limo',hierba:'Hierba / algas',roca:'Roca',duro:'Duro (sin precisar)',mixto:'Mixto'};
let toastTimer;
function toast(text,error=false){$('toast').textContent=text;$('toast').classList.toggle('error',error);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,error?6500:3800);}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
// En iPhone, la hoja de Compartir permite guardar en Archivos/iCloud o enviar por WhatsApp. Devuelve false si se cancela.
async function shareOrDownload(name,text,type,title){try{const file=new File([text],name,{type});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title});return true;}}catch(e){if(e?.name==='AbortError')return false;}download(name,text,type);return true;}
async function copyText(text){try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(text);toast('Coordenadas copiadas.');}catch{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();const done=document.execCommand('copy');t.remove();toast(done?'Coordenadas copiadas.':text,!done);}}
const SOURCES={
 pnoa:{id:'pnoa',title:'Ortofoto PNOA · máxima actualidad',short:'PNOA',urls:['https://www.ign.es/wms-inspire/pnoa-ma'],layer:'OI.OrthoimageCoverage',credit:'PNOA · IGN / CNIG',doc:'https://www.ign.es/web/ign/portal/ide-area-nodo-ide-ign',match:/OrthoimageCoverage|PNOA/i},
 raster:{id:'raster',title:'Mapa topográfico actual · IGN',short:'IGN',urls:['https://www.ign.es/wms-inspire/mapa-raster'],layer:'mtn_rasterizado',credit:'IGN / CNIG · cartografía ráster',doc:'https://www.ign.es/web/ign/portal/ide-area-nodo-ide-ign',match:/mtn_rasterizado|mapa raster|cartograf.a raster/i},
 flight56:{id:'flight56',title:'Vuelo americano 1956–1957 · serie B',short:'1956–57',urls:['https://www.ign.es/wms/pnoa-historico'],layer:'AMS_1956-1957',credit:'PNOA histórico · IGN / CNIG y productores',doc:'https://pnoa.ign.es/pnoa-imagen/fotogramas-y-ortofotos-historicas',match:/AMS_1956-1957|1956.*1957/i},
 flight45:{id:'flight45',title:'Vuelo americano 1945–1946 · IDEEX',short:'1945–46',urls:['https://www.ideex.es/CICTEX/ortoVuelo1945','https://www.ideextremadura.com/CICTEX/ortoVuelo1945'],layer:'',credit:'Junta de Extremadura · CICTEX / IDEEX',doc:'https://geoportal.ideex.es/pages/ideex',match:/1945|1946|ortofoto|ortoimagen/i},
 mtn50:{id:'mtn50',title:'MTN50 · primera edición',short:'MTN50 histórico',urls:['https://www.ign.es/wms/primera-edicion-mtn'],layer:'mtn50-edicion1',credit:'IGN / CNIG · primera edición MTN50',doc:'https://www.ign.es/web/ign/portal/ide-area-nodo-ide-ign',match:/mtn50.edicion1|primera.*50/i},
 minutas:{id:'minutas',title:'Minutas MTN50 · catastrones',short:'Minutas MTN50',urls:['https://www.ign.es/wms/primera-edicion-mtn'],layer:'',credit:'IGN / CNIG · minutas MTN50',doc:'https://centrodedescargas.cnig.es/CentroDescargas/minutas-mtn50-catastrones',match:/minutas|catastrones/i},
 badajoz:{id:'badajoz',title:'Badajoz 1960–1967 · IDEEX',short:'Badajoz 1960–67',urls:['https://www.ideex.es/CICTEX/cartoBA45','https://www.ideextremadura.com/CICTEX/cartoBA45'],layer:'',credit:'Junta de Extremadura · CICTEX / IDEEX',doc:'https://geoportal.ideex.es/pages/ideex',match:/cartograf|1960|1967|badajoz/i}
};
// Fotografías en JPEG (5-8 veces menos datos que PNG) si el catálogo lo anuncia; planos en PNG.
// Las imágenes del IGN se piden directamente (una etiqueta <img> no necesita CORS); el proxy queda para catálogos y como reserva.
const PHOTO_SOURCES=['pnoa','flight56','flight45'];
for(const s of Object.values(SOURCES)){s.url=s.urls[0];s.version='1.3.0';s.crs='EPSG:3857';s.catalogState='Sin consultar';s.catalogError='';s.direct=s.urls.every(u=>new URL(u).hostname==='www.ign.es');s.format=s.direct&&PHOTO_SOURCES.includes(s.id)?'image/jpeg':'image/png';}
const defaults={base:'pnoa',photo:'flight56',topo:'mtn50',photoEnabled:true,topoEnabled:false,photoOpacity:100,topoOpacity:65,compare:'swipe',split:50,rings:true,ringsM:[200,250],wrapM:3.9,campLines:true,bathOpacity:75,center:[...HOME.center],zoom:HOME.zoom};
const STORAGE='orellana-atlas-v1';let storageWorks=true;
let state={settings:{...defaults},features:[],activeCampId:null,bath:null,updatedAt:null,lastBackupAt:null};
const KNOWN_SOURCES=['manual','flight56','flight45','mtn50','minutas','badajoz','sonar','import'];
function normalizedFeature(f){
 if(!f||f.type!=='Feature'||!f.geometry)return null;const g=f.geometry,p=f.properties||{};let geom;
 if(g.type==='Point'&&coordOK(g.coordinates))geom={type:'Point',coordinates:g.coordinates.slice(0,2)};
 else if(g.type==='LineString'&&Array.isArray(g.coordinates)&&g.coordinates.length>=2&&g.coordinates.length<=10000&&g.coordinates.every(coordOK))geom={type:'LineString',coordinates:g.coordinates.map(c=>c.slice(0,2))};
 else return null;
 const depth=p.depth_m===null||p.depth_m===undefined||p.depth_m===''?null:Number(p.depth_m);
 return {type:'Feature',id:typeof f.id==='string'?f.id:uid(),geometry:geom,properties:{name:String(p.name||'Sin nombre').slice(0,120),kind:Object.hasOwn(KINDS,p.kind)?p.kind:'point',landmark:String(p.landmark||'').slice(0,180),bottom:Object.hasOwn(BOTTOMS,p.bottom)?p.bottom:'',source:KNOWN_SOURCES.includes(p.source)?p.source:'import',depth_m:Number.isFinite(depth)&&depth>=0&&depth<=500?depth:null,observedAt:/^\d{4}-\d{2}-\d{2}$/.test(p.observedAt||'')?p.observedAt:'',waterReference:String(p.waterReference||'').slice(0,180),notes:String(p.notes||p.description||'').slice(0,2000),verified:p.verified===true,createdAt:String(p.createdAt||new Date().toISOString()),updatedAt:String(p.updatedAt||new Date().toISOString())}};
}
function normalizeSettings(s={}){const r={...defaults};for(const [k,allowed] of Object.entries({base:['pnoa','raster'],photo:['flight56','flight45'],topo:['mtn50','minutas','badajoz']}))if(allowed.includes(s[k]))r[k]=s[k];for(const k of ['photoEnabled','topoEnabled','rings'])if(typeof s[k]==='boolean')r[k]=s[k];for(const k of ['photoOpacity','topoOpacity','bathOpacity','split'])if(Number.isFinite(s[k]))r[k]=clamp(s[k],k==='split'?5:0,k==='split'?95:100);if(['swipe','blend','modern'].includes(s.compare))r.compare=s.compare;if(typeof s.campLines==='boolean')r.campLines=s.campLines;if(Number.isFinite(s.wrapM)&&s.wrapM>=1&&s.wrapM<=10)r.wrapM=s.wrapM;if(Array.isArray(s.ringsM)){const rings=s.ringsM.filter(v=>Number.isFinite(v)&&v>=10&&v<=2000).slice(0,4);if(rings.length)r.ringsM=rings;}if(coordOK(s.center))r.center=s.center.slice(0,2);if(Number.isFinite(s.zoom))r.zoom=clamp(s.zoom,5,20);return r;}
function safeWmsUrl(raw){const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password)throw Error('Usa una dirección HTTPS sin credenciales.');u.hash='';for(const k of [...u.searchParams.keys()])if(/^(service|request|version|layers|styles|crs|srs|bbox|width|height|format|transparent|exceptions)$/i.test(k))u.searchParams.delete(k);return u.toString();}
function normalizeBath(b){if(!b||typeof b!=='object'||!b.allowed)return null;try{return {id:'customBath',title:String(b.title||'WMS batimétrico').slice(0,100),short:'Batimetría',url:safeWmsUrl(b.url),layer:String(b.layer||'').slice(0,250),version:b.version==='1.1.1'?'1.1.1':'1.3.0',crs:'EPSG:3857',credit:String(b.credit||'Fuente externa').slice(0,300),allowed:true};}catch{return null;}}
try{const raw=localStorage.getItem(STORAGE);if(raw){const x=JSON.parse(raw);state.settings=normalizeSettings(x.settings);state.features=(Array.isArray(x.features)?x.features:[]).slice(0,3000).map(normalizedFeature).filter(Boolean);state.activeCampId=typeof x.activeCampId==='string'?x.activeCampId:null;state.bath=normalizeBath(x.bath);state.updatedAt=x.updatedAt||null;state.lastBackupAt=typeof x.lastBackupAt==='string'?x.lastBackupAt:null;}}catch{storageWorks=false;}
let saveTimer;
function save(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(STORAGE,JSON.stringify(state));storageWorks=true;$('saveState').textContent='Guardado local';}catch{storageWorks=false;$('saveState').textContent='Sin guardado persistente';$('storageInfo').textContent='El navegador no permite guardar de forma persistente. Exporta una copia antes de cerrar.';}}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(save,400);}
let map,slots,networkProxy=false,mode='pan',draft=[],gps=null,gpsWatch=null,alertDismissed=false;
function stopGps(){if(gpsWatch!==null)navigator.geolocation.clearWatch(gpsWatch);gpsWatch=null;gps=null;$('locateBtn').classList.remove('active');$('gpsMark').hidden=true;map?.render(false);}
const sourcePromises=new Map(),capPromises=new Map();
async function fetchTimed(url,ms=8500){const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),ms);try{const r=await fetch(url,{signal:ctrl.signal,credentials:'omit',cache:'no-cache'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r;}finally{clearTimeout(t);}}
function wmsRequest(source,params,direct=false){
 if(networkProxy&&SOURCES[source.id]&&!direct){const u=new URL('api/wms',location.href);u.searchParams.set('source',source.id);u.searchParams.set('endpoint',String(Math.max(0,source.urls.indexOf(source.url))));for(const[k,v]of Object.entries(params))u.searchParams.set(k,String(v));return u.toString();}
 const u=new URL(source.url);for(const[k,v]of Object.entries(params))u.searchParams.set(k,String(v));return u.toString();
}
function parseCapabilities(text){
 const xml=new DOMParser().parseFromString(text,'text/xml');if(xml.querySelector('parsererror'))throw Error('El servidor no devolvió un catálogo WMS válido.');
 const all=Array.from(xml.getElementsByTagNameNS('*','Layer'));if(!all.length)throw Error('No hay capas WMS en la respuesta.');
 const direct=(e,tag)=>Array.from(e.children).filter(c=>c.localName===tag);const result=[];
 for(const e of all){const name=direct(e,'Name')[0]?.textContent?.trim();if(!name)continue;let crs=[];for(let n=e;n&&n.nodeType===1;n=n.parentElement){crs.push(...direct(n,'CRS').map(a=>a.textContent.trim()),...direct(n,'SRS').flatMap(a=>a.textContent.trim().split(/\s+/)));}result.push({name,title:direct(e,'Title')[0]?.textContent?.trim()||name,crs:[...new Set(crs)],leaf:direct(e,'Layer').length===0});}
 const getMap=Array.from(xml.getElementsByTagNameNS('*','GetMap'))[0],formats=getMap?direct(getMap,'Format').map(f=>f.textContent.trim().toLowerCase()):[];
 return {version:xml.documentElement.getAttribute('version')||'1.3.0',layers:result,formats};
}
async function catalogFor(source){const url=wmsRequest(source,{SERVICE:'WMS',REQUEST:'GetCapabilities',VERSION:'1.3.0'});if(!capPromises.has(url)){const p=fetchTimed(url).then(r=>r.text()).then(parseCapabilities).catch(e=>{capPromises.delete(url);throw e;});capPromises.set(url,p);}return capPromises.get(url);}
function chooseLayer(source,cat){
 const merc=l=>l.crs.some(c=>/EPSG:(3857|900913|102100)$/i.test(c));
 let cand=cat.layers.filter(merc);if(!cand.length)throw Error('El catálogo no anuncia EPSG:3857 / Web Mercator.');
 const score=l=>{const t=`${l.name} ${l.title}`;let v=source.layer&&l.name===source.layer?200:0;if(source.match?.test(t))v+=60;if(l.leaf)v+=8;if(/situaci[oó]n|huella|enlace|distribuci|infoVuelos|cuadr[ií]cula/i.test(t))v-=120;if(source.id==='mtn50'&&/mtn25|minutas/i.test(t))v-=100;return v;};
 const matched=cand.filter(l=>(source.layer&&l.name===source.layer)||source.match?.test(`${l.name} ${l.title}`));if(matched.length)cand=matched;else if(!(['flight45','badajoz'].includes(source.id)&&cand.length===1&&cand[0].leaf))throw Error('No se ha identificado automáticamente la capa de imagen solicitada.');cand.sort((a,b)=>score(b)-score(a));if(score(cand[0])<=0)throw Error('No se ha identificado automáticamente la capa de imagen.');return cand[0];
}
async function resolveSource(key,force=false){
 const s=SOURCES[key];if(!s)return;if(sourcePromises.has(key)&&!force)return sourcePromises.get(key);
 const p=(async()=>{s.catalogState='Consultando catálogo…';s.catalogError='';refreshStatus();let last;
 for(let i=0;i<s.urls.length;i++){
  const attempt={...s,url:s.urls[i]};try{const cat=await catalogFor(attempt);const layer=chooseLayer(s,cat);const version=cat.version.startsWith('1.1')?'1.1.1':'1.3.0',crs=layer.crs.find(c=>c.toUpperCase()==='EPSG:3857')||layer.crs.find(c=>/EPSG:(900913|102100)$/i.test(c));const format=PHOTO_SOURCES.includes(key)&&cat.formats.includes('image/jpeg')?'image/jpeg':'image/png';const changed=s.layer!==layer.name||s.url!==attempt.url||s.version!==version||s.crs!==crs||s.format!==format;s.url=attempt.url;s.layer=layer.name;s.version=version;s.crs=crs;s.format=format;s.catalogState='Catálogo leído';s.catalogError='';s.availableLayers=cat.layers.filter(l=>l.leaf);if(changed||force){for(const slot of Object.values(slots||{}))if(slot.source?.id===key)slot.setSource(s,true);}refreshStatus();map?.render(true);return s;}catch(e){last=e;}
 }
 s.catalogState='Catálogo no accesible';s.catalogError=last?.name==='AbortError'?'Tiempo de espera agotado':String(last?.message||last||'Red / CORS');refreshStatus();return s;
 })();sourcePromises.set(key,p);return p;
}
class RasterSlot{
 constructor(el){this.el=el;this.source=null;this.tiles=new Map();this.current=[];this.visible=true;this.generation=0;}
 setSource(s,force=false){if(!force&&this.source?.id===s?.id&&this.source?.layer===s?.layer&&this.source?.url===s?.url)return;this.generation++;for(const t of this.tiles.values())clearTimeout(t.timer);this.tiles.clear();this.current=[];this.el.replaceChildren();this.source=s?{...s}:null;this.problem='';}
 setVisible(v){this.visible=v;this.el.style.display=v?'':'none';if(!v)this.current=[];}
 retry(){const s=this.source;if(s)this.setSource(s,true);}
 tileUrl(z,x,y,viaProxy=false){const n=2**(z-1);const step=2*MERC/n;const minx=-MERC+x*step,maxy=MERC-y*step;const q={SERVICE:'WMS',VERSION:this.source.version||'1.3.0',REQUEST:'GetMap',LAYERS:this.source.layer,STYLES:'',FORMAT:this.source.format||'image/png',TRANSPARENT:this.source.format==='image/jpeg'?'FALSE':'TRUE',WIDTH:512,HEIGHT:512,BBOX:[minx,maxy-step,minx+step,maxy].map(v=>v.toFixed(5)).join(',')};q[this.source.version==='1.1.1'?'SRS':'CRS']=this.source.crs||'EPSG:3857';return wmsRequest(this.source,q,!!this.source.direct&&!viaProxy);}
 update(m,requestNew){
 if(!this.visible||!this.source)return;if(!this.source.layer){this.current=[];return;}
 const z=Math.floor(m.zoom),world=256*2**z,scale=2**(m.zoom-z),c=xy(m.center),cx=c[0]*world,cy=c[1]*world;
 const max=2**(z-1)-1;const x0=clamp(Math.floor((cx-m.width/2/scale)/512),0,max),x1=clamp(Math.floor((cx+m.width/2/scale)/512),0,max),y0=clamp(Math.floor((cy-m.height/2/scale)/512),0,max),y1=clamp(Math.floor((cy+m.height/2/scale)/512),0,max);
 const want=[];for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)want.push({z,x,y,key:`${z}/${x}/${y}`,d:(x*512+256-cx)**2+(y*512+256-cy)**2});want.sort((a,b)=>a.d-b.d);this.current=want.map(t=>t.key);
 if(requestNew){for(const k of want){if(this.tiles.has(k.key))continue;const img=new Image();img.alt='';img.draggable=false;img.decoding='async';img.width=512;img.height=512;const gen=this.generation,t={...k,img,status:'pending',touched:performance.now()};this.tiles.set(k.key,t);this.el.append(img);const done=ok=>{if(gen!==this.generation)return;clearTimeout(t.timer);if(!ok&&this.source.direct&&networkProxy&&!t.viaProxy){t.viaProxy=true;t.timer=setTimeout(()=>done(false),23000);img.src=this.tileUrl(k.z,k.x,k.y,true);return;}t.status=ok?'loaded':'error';if(ok)img.classList.add('loaded');else img.classList.remove('loaded');refreshStatus();};img.onload=()=>done(img.naturalWidth>0);img.onerror=()=>done(false);t.timer=setTimeout(()=>done(false),23000);img.src=this.tileUrl(z,k.x,k.y);}}
 for(const [key,t]of this.tiles){const sc=2**(m.zoom-t.z),w=256*2**t.z;const x=(t.x*512-c[0]*w)*sc+m.width/2,y=(t.y*512-c[1]*w)*sc+m.height/2;t.img.style.transform=`translate(${x.toFixed(3)}px,${y.toFixed(3)}px) scale(${sc})`;t.img.style.zIndex=t.z===z?'2':'1';if(this.current.includes(key))t.touched=performance.now();}
 const currentDone=this.current.length&&this.current.every(k=>this.tiles.get(k)?.status==='loaded');if(currentDone){for(const[key,t]of this.tiles)if(t.z!==z){clearTimeout(t.timer);t.img.remove();this.tiles.delete(key);}}
 if(this.tiles.size>64){const old=[...this.tiles.entries()].filter(([k])=>!this.current.includes(k)).sort((a,b)=>a[1].touched-b[1].touched);for(const[k,t]of old.slice(0,this.tiles.size-64)){clearTimeout(t.timer);t.img.remove();this.tiles.delete(k);}}
 }
 stats(){if(!this.visible||!this.source)return {label:'Desactivado',type:'off',loaded:0,pending:0,error:0};if(!this.source.layer){const s=SOURCES[this.source.id];const fail=s?.catalogState==='Catálogo no accesible';return {label:fail?'No se pudo resolver la capa. Ver Conexión.':'Identificando capa en el catálogo…',type:fail?'error':'pending',loaded:0,pending:fail?0:1,error:fail?1:0};}
 const a=this.current.map(k=>this.tiles.get(k)).filter(Boolean);const loaded=a.filter(t=>t.status==='loaded').length,pending=a.filter(t=>t.status==='pending').length,error=a.filter(t=>t.status==='error').length;
 if(pending)return {label:`Cargando imágenes${loaded?` · ${loaded} recibidas`:''}…`,type:'pending',loaded,pending,error};if(error)return {label:loaded?`${loaded} imágenes recibidas · ${error} fallidas`:'No se reciben imágenes. Reintentar en Conexión.',type:'error',loaded,pending,error};if(loaded)return {label:`${loaded} imágenes recibidas · cobertura a contrastar`,type:'ok',loaded,pending,error};return {label:'Preparando peticiones…',type:'pending',loaded,pending:1,error};}
}
class AtlasMap{
 constructor(el){this.el=el;this.center=[...state.settings.center];this.zoom=state.settings.zoom;this.width=0;this.height=0;this.pointers=new Map();this.dragInfo=null;this.reqTimer=null;this.lastTap=0;this.frame=null;this.needsTiles=false;this.installEvents();new ResizeObserver(()=>this.resize()).observe(el);this.resize();}
 resize(){const r=this.el.getBoundingClientRect();this.width=r.width;this.height=r.height;this.render(true);}
 project(c){const a=xy(c),b=xy(this.center),w=256*2**this.zoom;return [(a[0]-b[0])*w+this.width/2,(a[1]-b[1])*w+this.height/2];}
 unproject(p){const c=xy(this.center),w=256*2**this.zoom;return lonlat([c[0]+(p[0]-this.width/2)/w,c[1]+(p[1]-this.height/2)/w]);}
 pixelEvent(e){const r=this.el.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top];}
 setView(center,zoom=this.zoom){this.center=[clamp(center[0],-179.9,179.9),clamp(center[1],-80,80)];this.zoom=clamp(zoom,5,20);this.commit();this.render(true);}
 zoomAt(newZoom,p=[this.width/2,this.height/2]){const anchor=xy(this.unproject(p));this.zoom=clamp(newZoom,5,20);const w=256*2**this.zoom;this.center=lonlat([anchor[0]-(p[0]-this.width/2)/w,anchor[1]-(p[1]-this.height/2)/w]);this.render(false);clearTimeout(this.reqTimer);this.reqTimer=setTimeout(()=>{this.commit();this.render(true);},150);}
 commit(){state.settings.center=this.center.slice();state.settings.zoom=this.zoom;scheduleSave();}
 fit(coords){if(!coords.length)return;if(coords.length===1){this.setView(coords[0],17);return;}const q=coords.map(xy),minx=Math.min(...q.map(p=>p[0])),maxx=Math.max(...q.map(p=>p[0])),miny=Math.min(...q.map(p=>p[1])),maxy=Math.max(...q.map(p=>p[1]));const zx=Math.log2(Math.max(50,this.width-120)/(256*Math.max(1e-8,maxx-minx))),zy=Math.log2(Math.max(50,this.height-150)/(256*Math.max(1e-8,maxy-miny)));this.setView(lonlat([(minx+maxx)/2,(miny+maxy)/2]),Math.min(zx,zy,18));}
 render(requestNew=false){this.needsTiles||=requestNew;if(this.frame)return;this.frame=requestAnimationFrame(()=>{this.frame=null;const r=this.needsTiles;this.needsTiles=false;if(slots)for(const s of Object.values(slots))s.update(this,r);drawVectors();updateMapHud();refreshStatus();});}
 installEvents(){
 const el=this.el;
 el.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;if(e.target.closest?.('[data-point-id]'))return;e.preventDefault();el.focus({preventScroll:true});const p=this.pixelEvent(e);this.pointers.set(e.pointerId,p);el.setPointerCapture(e.pointerId);if(this.pointers.size===1)this.dragInfo={start:p,last:p,center:xy(this.center),moved:false,pinched:false};else{this.dragInfo.moved=true;this.dragInfo.pinched=true;const a=[...this.pointers.values()];this.dragInfo.pinchDist=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);this.dragInfo.pinchZoom=this.zoom;this.dragInfo.pinchAnchor=xy(this.unproject([(a[0][0]+a[1][0])/2,(a[0][1]+a[1][1])/2]));}el.classList.add('dragging');});
 el.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;const p=this.pixelEvent(e);this.pointers.set(e.pointerId,p);const d=this.dragInfo;if(this.pointers.size>=2){const a=[...this.pointers.values()],mid=[(a[0][0]+a[1][0])/2,(a[0][1]+a[1][1])/2],len=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);this.zoom=clamp(d.pinchZoom+Math.log2(Math.max(1,len)/Math.max(1,d.pinchDist)),5,20);const w=256*2**this.zoom;this.center=lonlat([d.pinchAnchor[0]-(mid[0]-this.width/2)/w,d.pinchAnchor[1]-(mid[1]-this.height/2)/w]);d.moved=true;}else{const dx=p[0]-d.start[0],dy=p[1]-d.start[1];if(Math.hypot(dx,dy)>5)d.moved=true;const w=256*2**this.zoom;this.center=lonlat([d.center[0]-dx/w,d.center[1]-dy/w]);}this.center[0]=clamp(this.center[0],-179.8,179.8);this.center[1]=clamp(this.center[1],-80,80);this.render(false);});
 const end=(e,cancel=false)=>{if(!this.pointers.has(e.pointerId))return;const p=this.pixelEvent(e),d=this.dragInfo;this.pointers.delete(e.pointerId);if(this.pointers.size===1){const q=[...this.pointers.values()][0];d.start=q;d.center=xy(this.center);d.moved=true;}if(this.pointers.size===0){el.classList.remove('dragging');if(!cancel&&!d.moved&&!d.pinched){if(mode!=='pan')onMapClick(this.unproject(p));else if(e.pointerType==='touch'){if(Date.now()-this.lastTap<300){this.zoomAt(this.zoom+1,p);this.lastTap=0;}else this.lastTap=Date.now();}}this.commit();this.render(true);this.dragInfo=null;}};
 el.addEventListener('pointerup',e=>end(e));el.addEventListener('pointercancel',e=>end(e,true));
 el.addEventListener('wheel',e=>{e.preventDefault();const d=clamp(-e.deltaY*.0025,-.8,.8);this.zoomAt(this.zoom+d,this.pixelEvent(e));},{passive:false});
 el.addEventListener('dblclick',e=>{e.preventDefault();if(mode==='pan')this.zoomAt(this.zoom+1,this.pixelEvent(e));});
 el.addEventListener('keydown',e=>{if(e.target!==el)return;let dx=0,dy=0;if(e.key==='ArrowLeft')dx=-100;if(e.key==='ArrowRight')dx=100;if(e.key==='ArrowUp')dy=-100;if(e.key==='ArrowDown')dy=100;if(dx||dy){e.preventDefault();this.setView(this.unproject([this.width/2+dx,this.height/2+dy]));}if(['+','='].includes(e.key)){e.preventDefault();this.zoomAt(this.zoom+1);}if(e.key==='-'){e.preventDefault();this.zoomAt(this.zoom-1);}});
 }
}
function activeCamp(){return state.features.find(f=>f.id===state.activeCampId&&f.geometry.type==='Point'&&f.properties.kind==='camp')||state.features.find(f=>f.geometry.type==='Point'&&f.properties.kind==='camp')||null;}
function polyPath(coords){return coords.map((c,i)=>{const p=map.project(c);return `${i?'L':'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`;}).join(' ');}
function drawVectors(){if(!map)return;let s='';const camp=activeCamp();const ringColors=['#71dfc3','#e4b478','#ff9e92','#b99cff'];if(camp&&state.settings.rings){for(const[m,color]of state.settings.ringsM.map((m,i)=>[m,ringColors[i%4]])){const pts=Array.from({length:73},(_,i)=>destination(camp.geometry.coordinates,m,i*5));s+=`<path d="${polyPath(pts)}Z" fill="${color}" fill-opacity=".035" stroke="${color}" stroke-width="1.5" stroke-dasharray="6 5"/>`;const p=map.project(destination(camp.geometry.coordinates,m,75));s+=`<text x="${p[0]+5}" y="${p[1]-5}" class="map-label" style="fill:${color}">${m} m · ${(m/state.settings.wrapM).toFixed(0)} v</text>`;}}
 if(camp&&state.settings.campLines){const cp=map.project(camp.geometry.coordinates);for(const f of state.features){if(f.geometry.type!=='Point'||f.id===camp.id||f.properties.kind==='camp')continue;const p=map.project(f.geometry.coordinates);s+=`<line x1="${cp[0].toFixed(1)}" y1="${cp[1].toFixed(1)}" x2="${p[0].toFixed(1)}" y2="${p[1].toFixed(1)}" stroke="${KINDS[f.properties.kind][1]}" stroke-opacity=".55" stroke-width="1.5" stroke-dasharray="3 5"/>`;}}
 for(const f of state.features){if(f.geometry.type==='LineString'){s+=`<path d="${polyPath(f.geometry.coordinates)}" fill="none" stroke="#0e2530" stroke-width="6"/><path d="${polyPath(f.geometry.coordinates)}" fill="none" stroke="#e4b478" stroke-width="2.5"/>`;}}
 if(gps){const p=map.project(gps.coords),q=map.project(destination(gps.coords,gps.accuracy,90)),rad=Math.hypot(q[0]-p[0],q[1]-p[1]);s+=`<circle cx="${p[0]}" cy="${p[1]}" r="${rad}" fill="#77bfff" fill-opacity=".12" stroke="#77bfff"/><circle cx="${p[0]}" cy="${p[1]}" r="6" fill="#77bfff" stroke="#fff" stroke-width="2"/>`;}
 for(const f of state.features.filter(f=>f.geometry.type==='Point')){const p=map.project(f.geometry.coordinates);if(p[0]<-250||p[0]>map.width+250||p[1]<-100||p[1]>map.height+100)continue;const c=KINDS[f.properties.kind][1],sub=camp&&state.settings.campLines&&f.id!==camp.id&&f.properties.kind!=='camp'?`<text x="19" y="18" class="map-label sub">${fmtFromCamp(camp.geometry.coordinates,f.geometry.coordinates).short}</text>`:'';const shape=f.properties.kind==='camp'?'<path d="M-8 7 0-8 8 7Z" fill="currentColor" stroke="#18303b" stroke-width="1.5"/>':'<circle r="5" fill="currentColor"/>';s+=`<g class="point-marker" data-point-id="${esc(f.id)}" tabindex="0" role="button" aria-label="Editar ${esc(f.properties.name)}" transform="translate(${p[0].toFixed(1)} ${p[1].toFixed(1)})" style="color:${c}"><circle r="24" fill="transparent"/><circle r="14" fill="#0f2834" stroke="${c}" stroke-width="2"/>${shape}<text x="19" y="4" class="map-label">${esc(f.properties.name.slice(0,34))}</text>${sub}</g>`;}
 if(draft.length){s+=`<path d="${polyPath(draft)}" fill="none" stroke="#0c1c26" stroke-width="6"/><path d="${polyPath(draft)}" fill="none" stroke="#fff1a8" stroke-width="2.5" stroke-dasharray="7 4"/>`;for(let i=0;i<draft.length;i++){const p=map.project(draft[i]);s+=`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="#fff1a8" stroke="#173542" stroke-width="2"/><text x="${p[0]+8}" y="${p[1]-9}" class="map-label">${i+1}</text>`;}}
 $('vectors').innerHTML=s;
}
function updateMapHud(){if(!map)return;const c=map.center;$('centerCoords').textContent=`${c[1].toFixed(5)}, ${c[0].toFixed(5)}`;const mpp=Math.cos(c[1]*DEG)*2*Math.PI*R/(256*2**map.zoom);const target=mpp*110,pow=10**Math.floor(Math.log10(target)),size=[1,2,5,10].map(n=>n*pow).filter(n=>n<=target).pop()||pow;$('scaleText').textContent=fmtDist(size);$('scaleBar').style.width=`${size/mpp}px`;applyComparison();}
let statusFrame;
function refreshStatus(){if(statusFrame)return;statusFrame=requestAnimationFrame(()=>{statusFrame=null;if(!slots)return;const base=slots.base.stats(),photo=slots.photo.stats(),topo=slots.topo.stats(),bath=slots.bath.stats();for(const[id,v]of [['baseStatus',base],['photoStatus',photo],['topoStatus',topo],['bathStatus',bath]]){$(id).textContent=v.label;$(id).className=`status ${v.type}`;}
 if(!state.bath){$('bathStatus').textContent='Sin fuente configurada';$('bathStatus').className='status';}$('bathyBadge').textContent=state.bath?(bath.type==='ok'?'IMÁGENES RECIBIDAS':'CONFIGURADA'):'SIN CONECTAR';$('bathyBadge').className=`pill ${state.bath&&bath.type==='ok'?'green':'amber'}`;
 const list=[base,photo,topo,bath],loaded=list.reduce((a,b)=>a+b.loaded,0),pending=list.reduce((a,b)=>a+b.pending,0);$('loadingLine').hidden=!pending;$('mapWelcome').hidden=loaded>0;
 $('historicLabel').textContent=historicName()+((photo.type==='error'&&slots.photo.visible)||(topo.type==='error'&&slots.topo.visible)?' · capa no recibida':'');$('modernLabel').textContent=SOURCES[state.settings.base].short+(base.type==='error'?' · sin imagen':'');
 if(!pending&&loaded===0){$('welcomeText').textContent='No se han recibido mapas. Consulta el panel Conexión para reintentar o revisar el servicio.';}
 if(list.some(a=>a.error)&&!alertDismissed){$('mapAlert').hidden=false;$('mapAlert').querySelector('strong').textContent=loaded?'Una capa no se está mostrando completa':'No se han recibido imágenes del mapa';$('mapAlertText').textContent=loaded?'El mapa visible puede ser la capa inferior. Revisa el estado antes de interpretar una imagen como histórica.':'Comprueba Internet y el estado de las fuentes. Tus puntos y herramientas no dependen de estas imágenes.';}else if(!list.some(a=>a.error))$('mapAlert').hidden=true;
 updateDiagnostics();});}
function historicName(){const a=[];if(state.settings.photoEnabled)a.push(SOURCES[state.settings.photo].short);if(state.settings.topoEnabled)a.push(SOURCES[state.settings.topo].short);return a.join(' + ')||'Histórico desactivado';}
function applyComparison(){if(!slots)return;const s=state.settings,visible=s.compare!=='modern';$('oldGroup').style.display=visible?'':'none';$('oldGroup').style.clipPath=s.compare==='swipe'?`inset(0 ${100-s.split}% 0 0)`:'none';$('swipe').hidden=s.compare!=='swipe'||(!s.photoEnabled&&!s.topoEnabled);$('swipe').style.left=`${s.split}%`;$('swipeHandle').setAttribute('aria-valuenow',Math.round(s.split));$('historicTag').hidden=!visible||(!s.photoEnabled&&!s.topoEnabled);$('photoRaster').style.opacity=s.photoOpacity/100;$('topoRaster').style.opacity=s.topoOpacity/100;$('bathRaster').style.opacity=s.bathOpacity/100;}
// Keep all synchronization local; no state is sent with point or note contents.
function syncControls(){const s=state.settings;$('baseSelect').value=s.base;$('photoEnabled').checked=s.photoEnabled;$('topoEnabled').checked=s.topoEnabled;$('topoSelect').value=s.topo;$('ringsEnabled').checked=s.rings;$('campLines').checked=s.campLines;$('wrapM').value=String(s.wrapM).replace('.',',');$('ringsM').value=s.ringsM.join(' ');for(const[k,input,label]of [['photoOpacity','photoOpacity','photoValue'],['topoOpacity','topoOpacity','topoValue'],['bathOpacity','bathOpacity','bathValue'],['split','swipeRange','swipeValue']]){$(input).value=s[k];$(label).textContent=`${Math.round(s[k])} %`;}$$('[data-photo]').forEach(e=>e.classList.toggle('active',e.dataset.photo===s.photo));$$('[data-compare]').forEach(e=>e.classList.toggle('active',e.dataset.compare===s.compare));$('swipeControls').hidden=s.compare!=='swipe';$('comparisonHint').textContent=s.compare==='blend'?'Ajusta la opacidad de fotografía y plano. Con el 100 % la capa superior oculta la inferior.':s.compare==='modern'?'Solo se muestra el mapa actual y tus datos. La configuración histórica se conserva.':'Arrastra el separador sobre el mapa. Puedes mostrar fotografía y plano a la vez.';$('bathOpacityWrap').hidden=!state.bath;if(state.bath){$('bathName').value=state.bath.title;$('bathUrl').value=state.bath.url;$('bathLayer').value=state.bath.layer;$('bathVersion').value=state.bath.version;$('bathCredit').value=state.bath.credit;$('bathAllowed').checked=true;}}
function applySources(){if(!slots)return;const s=state.settings;slots.base.setSource(SOURCES[s.base]);slots.base.setVisible(true);slots.photo.setSource(SOURCES[s.photo]);slots.photo.setVisible(s.photoEnabled&&s.compare!=='modern');slots.topo.setSource(SOURCES[s.topo]);slots.topo.setVisible(s.topoEnabled&&s.compare!=='modern');slots.bath.setSource(state.bath);slots.bath.setVisible(!!state.bath);for(const slot of [slots.base,slots.photo,slots.topo])if(slot.visible)resolveSource(slot.source.id);syncControls();applyComparison();updateAttribution();map.render(true);save();}
function updateAttribution(){const a=[...new Map(Object.values(slots).filter(s=>s.visible&&s.source).map(s=>[s.source.id,s.source])).values()];$('attribution').innerHTML=a.map(s=>s.doc?`<a href="${esc(s.doc)}" target="_blank" rel="noopener noreferrer">${esc(s.credit)}</a>`:esc(s.credit)).join(' · ');}
function updateDiagnostics(){if(!$('sourceDiagnostics'))return;const active=[...new Set(Object.values(slots).filter(s=>s.visible&&s.source&&s.source.id!=='customBath').map(s=>s.source.id))];const html=active.map(id=>{const s=SOURCES[id],slot=Object.values(slots).find(x=>x.visible&&x.source?.id===id),v=slot.stats();const caps=wmsRequest(s,{SERVICE:'WMS',REQUEST:'GetCapabilities',VERSION:'1.3.0'});return `<div class="status-card"><strong>${esc(s.title)}</strong><code>${esc(s.url)}<br>Capa: ${esc(s.layer||'identificación automática pendiente')}</code><div class="status ${v.type}">${esc(v.label)}</div><p class="tiny" style="margin:7px 0">${esc(s.catalogState)}${s.catalogError?` · ${esc(s.catalogError)}`:''}</p><div class="row between"><button data-catalog="${id}">Releer catálogo</button><a href="${esc(caps)}" target="_blank" rel="noopener noreferrer">Ver WMS ↗</a></div></div>`;}).join('');if($('sourceDiagnostics').innerHTML!==html)$('sourceDiagnostics').innerHTML=html;}
function openSidebar(tab){if(tab)selectTab(tab);document.body.classList.add('sidebar-open');}
function closeSidebar(){document.body.classList.remove('sidebar-open');}
function selectTab(tab){$$('[data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===tab));for(const t of ['layers','points','bathy','settings'])$(`tab-${t}`).classList.toggle('hidden',t!==tab);}
function renderFeatures(){const points=state.features.filter(f=>f.geometry.type==='Point'),traces=state.features.filter(f=>f.geometry.type==='LineString'),camp=activeCamp();$('pointsCount').textContent=points.length;const rings=state.settings.ringsM.map(m=>`${m} m`).join(', ');$('campSummary').textContent=camp?`Puesto activo: ${camp.properties.name}. Radios: ${rings}.`:`Marca un puesto para ver los radios (${rings}), las distancias en vueltas y el rumbo a cada punto.`;
 $('pointsList').innerHTML=points.length?points.map(f=>{const p=f.properties,c=f.geometry.coordinates,d=camp&&camp.id!==f.id?fmtFromCamp(camp.geometry.coordinates,c).text:null;return `<article class="point-card"><div class="row between"><h3>${esc(p.name)}</h3><span class="pill" style="color:${KINDS[p.kind][1]}">${esc(KINDS[p.kind][0])}</span></div><div class="meta">${c[1].toFixed(6)}, ${c[0].toFixed(6)}${d!==null?`<br><span style="color:var(--accent)">Desde el puesto: ${d}</span>`:''}${p.landmark?`<br>Alineación: ${esc(p.landmark)}`:''}${p.bottom?`<br>Fondo: ${esc(BOTTOMS[p.bottom])}`:''}${p.depth_m!==null?`<br>Profundidad registrada: ${p.depth_m.toFixed(2).replace('.',',')} m`:''}<br>${esc(p.verified?'Contrastado en campo':'Pendiente de contrastar')}</div><div class="row"><button data-view-point="${esc(f.id)}">Ver</button><button data-edit-point="${esc(f.id)}">Editar</button>${p.kind==='camp'?`<button data-active-camp="${esc(f.id)}">${camp?.id===f.id?'Puesto activo':'Activar'}</button>`:''}</div></article>`;}).join(''):`<div class="empty"><svg class="icon"><use href="#i-pin"/></svg>Aún no hay puntos guardados.<br>Marca tu puesto y empieza a registrar lo que observes.</div>`;
 updateBackupReminder();$('tracesList').innerHTML=traces.map(f=>`<article class="point-card"><h3>${esc(f.properties.name)}</h3><div class="meta">${fmtDist(pathLength(f.geometry.coordinates))} · ${fmtWraps(pathLength(f.geometry.coordinates))} · ${f.geometry.coordinates.length} vértices</div><div class="row"><button data-view-trace="${esc(f.id)}">Ver</button><button data-delete-trace="${esc(f.id)}" class="danger">Eliminar</button></div></article>`).join('');map?.render(false);}
function setMode(next){if(mode==='measure'&&draft.length>1&&next!=='measure'&&!confirm('El trazado no está guardado. ¿Descartarlo?'))return;mode=next;draft=[];closeSidebar();$('map').classList.toggle('tool',mode!=='pan');for(const[id,m]of [['addPoint','point'],['setCamp','camp'],['measureBtn','measure']])$(id).classList.toggle('active',mode===m);$('actionBar').hidden=mode==='pan';$('gpsMark').hidden=!gps||mode!=='pan';$('undoMeasure').hidden=mode!=='measure';$('saveTrace').hidden=mode!=='measure';$('cancelTool').textContent=mode==='measure'?'Terminar':'Cancelar';updateAction();map?.render(false);}
function updateAction(){const t=mode==='measure'?`${draft.length?`${fmtDist(pathLength(draft))} · ${fmtWraps(pathLength(draft))}`:'Medir un recorrido'}<small>Toca el mapa para añadir vértices. Guarda para conservarlo.</small>`:mode==='camp'?'Toca el mapa para colocar tu puesto.<small>Después podrás ajustar las coordenadas.</small>':mode==='sounding'?'Toca el lugar donde has medido con la sonda.<small>Indica la profundidad y su fecha en la ficha.</small>':'Toca el mapa para añadir un punto.<small>Selecciona su origen y añade tus notas.</small>';$('actionLabel').innerHTML=t;$('saveTrace').disabled=draft.length<2;$('undoMeasure').disabled=!draft.length;}
function onMapClick(c){if(mode==='measure'){draft.push(c);updateAction();map.render(false);return;}if(['point','camp','sounding'].includes(mode)){const kind=mode==='point'?'point':mode;openPoint(null,c,kind);mode='pan';$('actionBar').hidden=true;$('map').classList.remove('tool');for(const id of ['addPoint','setCamp','measureBtn'])$(id).classList.remove('active');}}
function updatePointInfo(){const camp=activeCamp(),c=[num($('pointLng').value),num($('pointLat').value)],id=$('pointId').value;$('pointFromCamp').textContent=!camp?'Marca un puesto para ver aquí la distancia en vueltas y el rumbo.':camp.id===id||$('pointKind').value==='camp'?'':coordOK(c)?`Desde el puesto «${camp.properties.name}»: ${fmtFromCamp(camp.geometry.coordinates,c).text}`:'';}
function openPoint(id,c,kind='point'){const f=id?state.features.find(x=>x.id===id):null;const p=f?.properties||{},coords=f?.geometry.coordinates||c||map.center;const suggested=state.settings.compare==='modern'?'manual':state.settings.topoEnabled?state.settings.topo:state.settings.photoEnabled?state.settings.photo:'manual';$('pointId').value=id||'';$('pointTitle').textContent=f?'Editar punto':kind==='camp'?'Marcar puesto':kind==='sounding'?'Registrar profundidad':'Nuevo punto';$('pointName').value=p.name||(kind==='camp'?'Mi puesto':kind==='sounding'?`Sonda ${state.features.filter(x=>x.properties.kind==='sounding').length+1}`:`${kind==='point'?'Punto':KINDS[kind][0]} ${state.features.filter(x=>x.geometry.type==='Point').length+1}`);$('pointKind').value=p.kind||kind;$('pointSource').value=p.source||(kind==='sounding'?'sonar':kind==='camp'?'manual':suggested);$('pointLat').value=coords[1].toFixed(6);$('pointLng').value=coords[0].toFixed(6);$('pointDepth').value=p.depth_m??'';$('pointDate').value=p.observedAt||today();$('pointWater').value=p.waterReference||'';$('pointNotes').value=p.notes||'';$('pointLandmark').value=p.landmark||'';$('pointBottom').value=p.bottom||'';$('useGps').hidden=!gps;updatePointInfo();$('pointVerified').checked=p.verified||false;$('deletePoint').hidden=!f;$('pointDialog').showModal();setTimeout(()=>$('pointName').focus(),50);}
$('pointForm').addEventListener('submit',e=>{e.preventDefault();const coords=[num($('pointLng').value),num($('pointLat').value)];if(!coordOK(coords)){toast('Revisa las coordenadas WGS84: latitud entre −85 y 85, longitud entre −180 y 180.',true);return;}const depth=$('pointDepth').value.trim()===''?null:num($('pointDepth').value);if(depth!==null&&(!Number.isFinite(depth)||depth<0||depth>500)){toast('Introduce una profundidad entre 0 y 500 metros, o deja el campo vacío.',true);return;}if(depth===null&&$('pointKind').value==='sounding'){toast('Una medición de sonda necesita la profundidad.',true);return;}if(depth!==null&&!$('pointDate').value){toast('Añade la fecha de la medición de profundidad.',true);return;}const id=$('pointId').value||uid(),old=state.features.find(f=>f.id===id),now=new Date().toISOString();const f={type:'Feature',id,geometry:{type:'Point',coordinates:coords},properties:{name:$('pointName').value.trim()||'Sin nombre',kind:$('pointKind').value,landmark:$('pointLandmark').value.trim(),bottom:$('pointBottom').value,source:$('pointSource').value,depth_m:depth,observedAt:$('pointDate').value,waterReference:$('pointWater').value.trim(),notes:$('pointNotes').value.trim(),verified:$('pointVerified').checked,createdAt:old?.properties.createdAt||now,updatedAt:now}};if(old)state.features[state.features.indexOf(old)]=f;else state.features.push(f);if(f.properties.kind==='camp'&&!activeCamp())state.activeCampId=id;if(f.properties.kind==='camp'&&!state.activeCampId)state.activeCampId=id;save();renderFeatures();$('pointDialog').close();toast('Punto guardado en este navegador.');});
$('deletePoint').addEventListener('click',()=>{const id=$('pointId').value,f=state.features.find(f=>f.id===id);if(!f||!confirm(`¿Eliminar «${f.properties.name}»?`))return;state.features=state.features.filter(f=>f.id!==id);if(state.activeCampId===id)state.activeCampId=null;save();renderFeatures();$('pointDialog').close();});
async function backup(){const payload={app:'orellana-atlas',schemaVersion:1,exportedAt:new Date().toISOString(),...state};if(!await shareOrDownload(`Orellana_Atlas_${today()}.json`,JSON.stringify(payload,null,2),'application/json','Copia de Orellana Atlas'))return;state.lastBackupAt=new Date().toISOString();save();updateBackupReminder();toast('Copia completa exportada. Guárdala en Archivos o iCloud.');}
// Recordatorio: hay cambios sin copia desde hace más de 3 días (o nunca se hizo una).
function needsBackup(){if(!state.features.length)return false;const last=Date.parse(state.lastBackupAt||0)||0,changed=Math.max(0,...state.features.map(f=>Date.parse(f.properties.updatedAt)||0));return changed>last&&Date.now()-Math.max(last,Math.min(...state.features.map(f=>Date.parse(f.properties.createdAt)||Date.now())))>3*864e5;}
function updateBackupReminder(){const n=needsBackup();for(const id of ['exportTop','backupBtn'])$(id).classList.toggle('attention',n);$('backupHint').hidden=!n;}
async function sharePoints(){const text=JSON.stringify({type:'FeatureCollection',name:'Orellana Atlas · compartido',features:state.features},null,2);if(await shareOrDownload(`Orellana_compartir_${today()}.geojson`,text,'application/geo+json','Puntos de Orellana Atlas'))toast('Tu compañero puede importarlo en «Importar». Los puntos repetidos se actualizan, no se duplican.');}
function exportGeo(){download(`Orellana_puntos_trazados_${today()}.geojson`,JSON.stringify({type:'FeatureCollection',name:'Orellana Atlas',features:state.features},null,2),'application/geo+json');}
function exportGPX(){const point=(f)=>{const p=f.properties,c=f.geometry.coordinates;const desc=[p.notes,p.depth_m!==null?`Profundidad registrada: ${p.depth_m} m`:'',p.observedAt?`Fecha: ${p.observedAt}`:'',p.waterReference?`Referencia agua: ${p.waterReference}`:'',`Origen: ${p.source}`].filter(Boolean).join('\n');return `<wpt lat="${c[1]}" lon="${c[0]}"><name>${esc(p.name)}</name><desc>${esc(desc)}</desc><type>${esc(p.kind)}</type><extensions><oa:source>${esc(p.source)}</oa:source>${p.depth_m!==null?`<oa:depth_m>${p.depth_m}</oa:depth_m>`:''}<oa:observedAt>${esc(p.observedAt)}</oa:observedAt><oa:waterReference>${esc(p.waterReference)}</oa:waterReference>${p.landmark?`<oa:landmark>${esc(p.landmark)}</oa:landmark>`:''}${p.bottom?`<oa:bottom>${esc(p.bottom)}</oa:bottom>`:''}</extensions></wpt>`;};const tracks=state.features.filter(f=>f.geometry.type==='LineString').map(f=>`<trk><name>${esc(f.properties.name)}</name><desc>${esc(f.properties.notes)}</desc><trkseg>${f.geometry.coordinates.map(c=>`<trkpt lat="${c[1]}" lon="${c[0]}"/>`).join('')}</trkseg></trk>`);const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Orellana Atlas" xmlns="http://www.topografix.com/GPX/1/1" xmlns:oa="urn:orellana-atlas:1"><metadata><name>Orellana Atlas</name><time>${new Date().toISOString()}</time></metadata>${state.features.filter(f=>f.geometry.type==='Point').map(point).join('')}${tracks.join('')}</gpx>`;download(`Orellana_${today()}.gpx`,xml,'application/gpx+xml');}
function parseGPX(text){const doc=new DOMParser().parseFromString(text,'text/xml');if(doc.querySelector('parsererror'))throw Error('El GPX no es XML válido.');const children=(e,tag)=>Array.from(e.children).find(c=>c.localName===tag)?.textContent||'';const ext=(e,tag)=>Array.from(e.getElementsByTagNameNS('*',tag))[0]?.textContent||'';const f=[];for(const w of Array.from(doc.getElementsByTagNameNS('*','wpt'))){f.push({type:'Feature',geometry:{type:'Point',coordinates:[num(w.getAttribute('lon')),num(w.getAttribute('lat'))]},properties:{name:children(w,'name'),kind:children(w,'type'),notes:children(w,'desc'),source:ext(w,'source')||'import',depth_m:ext(w,'depth_m')||null,observedAt:ext(w,'observedAt'),waterReference:ext(w,'waterReference'),landmark:ext(w,'landmark'),bottom:ext(w,'bottom')}});}for(const tag of ['trkseg','rte'])for(const t of Array.from(doc.getElementsByTagNameNS('*',tag))){const pts=Array.from(t.getElementsByTagNameNS('*',tag==='rte'?'rtept':'trkpt')).map(p=>[num(p.getAttribute('lon')),num(p.getAttribute('lat'))]);f.push({type:'Feature',geometry:{type:'LineString',coordinates:pts},properties:{name:children(tag==='rte'?t:t.parentElement,'name')||'Trazado GPX',notes:children(tag==='rte'?t:t.parentElement,'desc'),source:'import'}});}return f;}
$('fileInput').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>5*1024*1024)throw Error('El archivo supera el límite de 5 MB.');const text=await file.text();let data,arr,replace=false;if(file.name.toLowerCase().endsWith('.gpx')||text.trim().startsWith('<'))arr=parseGPX(text);else{data=JSON.parse(text);if(data.app==='orellana-atlas'&&data.schemaVersion===1){if(!confirm('Restaurar esta copia sustituirá los puntos, trazados y ajustes actuales. ¿Continuar?'))return;replace=true;arr=data.features;}else if(data.type==='FeatureCollection')arr=data.features;else if(data.type==='Feature')arr=[data];else throw Error('Formato no reconocido. Usa una copia del atlas, GeoJSON o GPX.');}if(!Array.isArray(arr))throw Error('No se ha encontrado una lista de elementos válida.');if(arr.length>3000)throw Error('Máximo 3.000 elementos por proyecto.');const features=arr.map(normalizedFeature).filter(Boolean),rejected=arr.length-features.length;if(!features.length&&arr.length)throw Error('No hay puntos ni líneas con coordenadas WGS84 válidas.');if(replace){state={settings:normalizeSettings(data.settings),features,activeCampId:typeof data.activeCampId==='string'?data.activeCampId:null,bath:normalizeBath(data.bath),updatedAt:null,lastBackupAt:new Date().toISOString()};map.setView(state.settings.center,state.settings.zoom);applySources();}else{if(state.features.length+features.length>3000)throw Error('El proyecto resultante supera los 3.000 elementos.');let added=0,updated=0,same=0;for(const f of features){const i=state.features.findIndex(x=>x.id===f.id);if(i<0){state.features.push(f);added++;}else if((Date.parse(f.properties.updatedAt)||0)>(Date.parse(state.features[i].properties.updatedAt)||0)){state.features[i]=f;updated++;}else same++;}features.summary=`${added} nuevos · ${updated} actualizados${same?` · ${same} ya estaban`:''}`;if(features.length){const coords=features.flatMap(f=>f.geometry.type==='Point'?[f.geometry.coordinates]:f.geometry.coordinates);map.fit(coords);}}save();renderFeatures();selectTab('points');updateBackupReminder();toast(`${features.summary||`${features.length} elementos importados`}${rejected?` · ${rejected} incompatibles omitidos`:''}.`,rejected>0);}catch(err){toast(err.message||'No se ha podido importar el archivo.',true);}});
function retryActive(){alertDismissed=false;for(const slot of Object.values(slots)){if(slot.visible){slot.retry();if(slot.source&&!slot.source.layer&&SOURCES[slot.source.id])resolveSource(slot.source.id,true);}}map.render(true);}
function wire(){
 $$('[data-tab]').forEach(e=>e.onclick=()=>selectTab(e.dataset.tab));$('openSidebar').onclick=()=>openSidebar();$('closeSidebar').onclick=closeSidebar;$('mobileScrim').onclick=closeSidebar;
 $$('[data-photo]').forEach(e=>e.onclick=()=>{state.settings.photo=e.dataset.photo;state.settings.photoEnabled=true;if(state.settings.compare==='modern')state.settings.compare='swipe';alertDismissed=false;applySources();});$('baseSelect').onchange=e=>{state.settings.base=e.target.value;alertDismissed=false;applySources();};$('topoSelect').onchange=e=>{state.settings.topo=e.target.value;state.settings.topoEnabled=true;alertDismissed=false;applySources();};$('photoEnabled').onchange=e=>{state.settings.photoEnabled=e.target.checked;applySources();};$('topoEnabled').onchange=e=>{state.settings.topoEnabled=e.target.checked;if(e.target.checked&&state.settings.compare==='modern')state.settings.compare='swipe';applySources();};
 $$('[data-compare]').forEach(e=>e.onclick=()=>{state.settings.compare=e.dataset.compare;applySources();});for(const[key,id,label]of [['photoOpacity','photoOpacity','photoValue'],['topoOpacity','topoOpacity','topoValue'],['bathOpacity','bathOpacity','bathValue'],['split','swipeRange','swipeValue']])$(id).addEventListener('input',e=>{state.settings[key]=Number(e.target.value);$(label).textContent=`${Math.round(state.settings[key])} %`;applyComparison();scheduleSave();});
 const handle=$('swipeHandle');let drag=false;handle.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();drag=true;handle.setPointerCapture(e.pointerId);});handle.addEventListener('pointermove',e=>{if(!drag)return;const r=$('mapShell').getBoundingClientRect();state.settings.split=clamp((e.clientX-r.left)/r.width*100,5,95);$('swipeRange').value=state.settings.split;$('swipeValue').textContent=`${Math.round(state.settings.split)} %`;applyComparison();});for(const evt of ['pointerup','pointercancel'])handle.addEventListener(evt,()=>{drag=false;save();});handle.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();state.settings.split=clamp(state.settings.split+(e.key==='ArrowLeft'?-2:2),5,95);syncControls();applyComparison();save();});
 $('zoomIn').onclick=()=>map.zoomAt(Math.floor(map.zoom)+1);$('zoomOut').onclick=()=>map.zoomAt(Math.ceil(map.zoom)-1);$('homeBtn').onclick=()=>map.setView(HOME.center,HOME.zoom);$('addPoint').onclick=$('addPointPanel').onclick=()=>setMode(mode==='point'?'pan':'point');$('setCamp').onclick=$('setCampPanel').onclick=()=>setMode(mode==='camp'?'pan':'camp');$('measureBtn').onclick=$('tracePanel').onclick=()=>setMode(mode==='measure'?'pan':'measure');$('addSounding').onclick=()=>setMode('sounding');$('ringsEnabled').onchange=e=>{state.settings.rings=e.target.checked;save();map.render(false);};$('cancelTool').onclick=()=>setMode('pan');$('undoMeasure').onclick=()=>{draft.pop();updateAction();map.render(false);};$('saveTrace').onclick=()=>{if(draft.length<2)return;$('traceName').value=`Trazado ${state.features.filter(f=>f.geometry.type==='LineString').length+1}`;$('traceNotes').value='';$('traceLength').textContent=`Longitud horizontal aproximada: ${fmtDist(pathLength(draft))}. Origen: ${historicName()}.`;$('traceDialog').showModal();};
 $('traceForm').onsubmit=e=>{e.preventDefault();const now=new Date().toISOString();state.features.push({type:'Feature',id:uid(),geometry:{type:'LineString',coordinates:draft.map(c=>c.slice())},properties:{name:$('traceName').value.trim()||'Trazado',kind:'point',landmark:'',bottom:'',source:state.settings.compare==='modern'?'manual':state.settings.topoEnabled?state.settings.topo:state.settings.photoEnabled?state.settings.photo:'manual',depth_m:null,observedAt:today(),waterReference:'',notes:$('traceNotes').value.trim(),verified:false,createdAt:now,updatedAt:now}});draft=[];setMode('pan');save();renderFeatures();$('traceDialog').close();toast('Trazado guardado.');};
 $('vectors').addEventListener('click',e=>{const g=e.target.closest('[data-point-id]');if(g){e.stopPropagation();openPoint(g.dataset.pointId);}});$('vectors').addEventListener('keydown',e=>{const g=e.target.closest('[data-point-id]');if(g&&['Enter',' '].includes(e.key)){e.preventDefault();openPoint(g.dataset.pointId);}});
 $('pointsList').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.viewPoint||b.dataset.editPoint||b.dataset.activeCamp,f=state.features.find(f=>f.id===id);if(!f)return;if(b.dataset.viewPoint){closeSidebar();map.setView(f.geometry.coordinates,17);}else if(b.dataset.editPoint)openPoint(id);else{state.activeCampId=id;save();renderFeatures();}};
 $('tracesList').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.viewTrace||b.dataset.deleteTrace,f=state.features.find(f=>f.id===id);if(!f)return;if(b.dataset.viewTrace){map.fit(f.geometry.coordinates);closeSidebar();}else if(confirm(`¿Eliminar «${f.properties.name}»?`)){state.features=state.features.filter(f=>f.id!==id);save();renderFeatures();}};
 for(const id of ['helpBtn','footHelp','sourcesBtn'])$(id).onclick=()=>$('helpDialog').showModal();$$('.close-dialog').forEach(e=>e.onclick=()=>e.closest('dialog').close());for(const d of $$('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$$('dialog[open]').length&&mode!=='pan')setMode('pan');});
 $('gotoBtn').onclick=()=>{$('gotoLat').value=map.center[1].toFixed(6);$('gotoLng').value=map.center[0].toFixed(6);$('gotoDialog').showModal();};$('gotoForm').onsubmit=e=>{e.preventDefault();const c=[num($('gotoLng').value),num($('gotoLat').value)];if(!coordOK(c)){toast('Coordenadas no válidas. Usa grados decimales WGS84.',true);return;}map.setView(c,16);$('gotoDialog').close();closeSidebar();};$('coordsBtn').onclick=()=>copyText(`${map.center[1].toFixed(6)}, ${map.center[0].toFixed(6)}`);
 $('locateBtn').onclick=()=>{if(gpsWatch!==null){stopGps();toast('GPS desactivado.');return;}if(!window.isSecureContext){toast('El GPS necesita HTTPS. En la prueba Wi-Fi puedes marcar el puesto manualmente.',true);return;}if(!navigator.geolocation){toast('La ubicación no está disponible en este navegador.',true);return;}toast('Buscando tu posición… El GPS seguirá activo hasta que vuelvas a pulsar el botón.');let first=true;$('locateBtn').classList.add('active');gpsWatch=navigator.geolocation.watchPosition(p=>{gps={coords:[p.coords.longitude,p.coords.latitude],accuracy:p.coords.accuracy};if(first){first=false;map.setView(gps.coords,Math.max(map.zoom,16));}$('gpsMark').hidden=mode!=='pan';$('gpsMark').querySelector('small').textContent=`±${Math.round(gps.accuracy)} m`;map.render(false);},e=>{stopGps();toast(e.code===1?'Permiso de ubicación no concedido. Puedes marcar el puesto manualmente.':'No se ha obtenido la ubicación. Comprueba el permiso del navegador.',true);},{enableHighAccuracy:true,timeout:20000,maximumAge:5000});};
 $('gpsMark').onclick=()=>{if(gps)openPoint(null,gps.coords,'point');};$('useGps').onclick=()=>{if(!gps)return;$('pointLat').value=gps.coords[1].toFixed(6);$('pointLng').value=gps.coords[0].toFixed(6);updatePointInfo();toast(`Coordenadas del GPS (±${Math.round(gps.accuracy)} m).`);};
 for(const id of ['pointLat','pointLng','pointKind'])$(id).addEventListener('input',updatePointInfo);$('sharePoints').onclick=sharePoints;
 $('wrapM').onchange=e=>{const v=num(e.target.value);if(!(v>=1&&v<=10)){toast('Metros por vuelta: entre 1 y 10.',true);e.target.value=String(state.settings.wrapM).replace('.',',');return;}state.settings.wrapM=v;save();renderFeatures();};
 $('ringsM').onchange=e=>{const v=e.target.value.split(/[\s;,]+/).map(v=>parseInt(v,10)).filter(x=>Number.isFinite(x)&&x>=10&&x<=2000).slice(0,4);if(!v.length){toast('Escribe uno a cuatro radios entre 10 y 2000 m, separados por espacios.',true);e.target.value=state.settings.ringsM.join(' ');return;}state.settings.ringsM=v;e.target.value=v.join(' ');save();renderFeatures();};
 $('campLines').onchange=e=>{state.settings.campLines=e.target.checked;save();map.render(false);};
 $('fullBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('mapShell').requestFullscreen)await $('mapShell').requestFullscreen();else toast('Este navegador no admite pantalla completa.');}catch{toast('No se ha podido abrir la pantalla completa.',true);}};
 for(const id of ['exportTop','backupBtn'])$(id).onclick=backup;$('exportGeo').onclick=exportGeo;$('exportGPX').onclick=exportGPX;for(const id of ['importBtn','importSettings'])$(id).onclick=()=>$('fileInput').click();
 $('retryAll').onclick=$('alertRetry').onclick=retryActive;$('alertConnections').onclick=()=>openSidebar('settings');$('alertHide').onclick=()=>{alertDismissed=true;$('mapAlert').hidden=true;};$('sourceDiagnostics').onclick=e=>{const b=e.target.closest('[data-catalog]');if(b){sourcePromises.delete(b.dataset.catalog);capPromises.clear();resolveSource(b.dataset.catalog,true);}};
 $('diagnosticExport').onclick=()=>{const out={app:'Orellana Atlas 0.3',date:new Date().toISOString(),mode:networkProxy?'proxy local':'directo',browser:navigator.userAgent,online:navigator.onLine,view:{center:map.center,zoom:map.zoom},sources:Object.fromEntries(Object.values(slots).filter(s=>s.source).map(s=>[s.source.id,{url:s.source.url,layer:s.source.layer,crs:s.source.crs,visible:s.visible,status:s.stats(),catalog:SOURCES[s.source.id]?.catalogState,error:SOURCES[s.source.id]?.catalogError}]))};download(`Orellana_diagnostico_${today()}.json`,JSON.stringify(out,null,2));};
 $('bathyForm').onsubmit=e=>{e.preventDefault();try{const url=safeWmsUrl($('bathUrl').value);state.bath=normalizeBath({title:$('bathName').value.trim(),url,layer:$('bathLayer').value.trim(),version:$('bathVersion').value,credit:$('bathCredit').value.trim(),allowed:$('bathAllowed').checked});if(!state.bath?.layer)throw Error('Indica el nombre técnico de la capa.');alertDismissed=false;applySources();toast('Conexión configurada. Comprueba las imágenes y su referencia de profundidad.');}catch(err){toast(err.message,true);}};$('removeBathy').onclick=()=>{if(state.bath&&!confirm('¿Quitar la conexión batimétrica configurada?'))return;state.bath=null;$('bathyForm').reset();applySources();};
 const online=()=>{$('offlineBanner').hidden=navigator.onLine;if(navigator.onLine)retryActive();};window.addEventListener('online',online);window.addEventListener('offline',online);$('offlineBanner').hidden=navigator.onLine;
 // iOS casi nunca dispara beforeunload: se guarda también al pasar la app a segundo plano.
 const flush=()=>{clearTimeout(saveTimer);state.settings.center=map.center;state.settings.zoom=map.zoom;save();};window.addEventListener('beforeunload',flush);window.addEventListener('pagehide',flush);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flush();});
}
async function init(){slots={base:new RasterSlot($('baseRaster')),photo:new RasterSlot($('photoRaster')),topo:new RasterSlot($('topoRaster')),bath:new RasterSlot($('bathRaster'))};map=new AtlasMap($('map'));wire();syncControls();renderFeatures();
 if(location.protocol==='http:'||location.protocol==='https:'){try{const r=await fetchTimed(new URL('api/health',location.href),1300),j=await r.json();networkProxy=j.app==='orellana-atlas';}catch{}}
 $('serverInfo').textContent=networkProxy?'Servidor del atlas activo. Los catálogos oficiales se consultan a través de un proxy limitado a IGN e IDEEX.':'Modo directo: las imágenes se piden al proveedor. Si el catálogo IDEEX falla por CORS, utiliza el lanzador del proyecto (server.py) o un despliegue con su proxy.';
 if(!window.isSecureContext && /^https?:$/.test(location.protocol)) $('serverInfo').textContent+=' Prueba por HTTP local: el GPS del móvil requiere una dirección HTTPS; puedes marcar el puesto a mano.';
 if(!storageWorks){$('saveState').textContent='Sin guardado persistente';$('storageInfo').textContent='Este navegador no permite guardar los datos de forma persistente. Exporta una copia antes de cerrar.';}
 try{await navigator.storage?.persist?.();}catch{}
 updateBackupReminder();if(needsBackup())toast('Tienes puntos sin copia desde hace días. Pulsa «Guardar copia» y guárdala en Archivos o iCloud.');
 applySources();setTimeout(()=>{if(Object.values(slots).every(s=>!s.stats().loaded)){if(!alertDismissed){$('mapAlert').hidden=false;$('mapAlertText').textContent='La conexión está tardando o no está disponible. Comprueba Internet y abre el panel Conexión.';}}},12000);
 // Read-only test surface. No synthetic map data is installed by the application.
 window.OrellanaAtlas={version:'0.3',project:xy,unproject:lonlat,distance,pathLength,destination,parseCapabilities,normalizeFeature:normalizedFeature,parseGPX,getState:()=>JSON.parse(JSON.stringify(state)),getView:()=>({center:map.center.slice(),zoom:map.zoom}),getStats:()=>Object.fromEntries(Object.entries(slots).map(([k,s])=>[k,s.stats()])),setView:(c,z)=>map.setView(c,z)};
}
init().catch(e=>{console.error(e);$('welcomeText').textContent='La aplicación no ha podido iniciarse. Abre el archivo en un navegador actualizado.';$('mapWelcome').hidden=false;toast('Error de inicio: '+(e.message||'desconocido'),true);});
})();
